server:
  port: 8088
logging:
  level:
    root: info
spring:
  main:
    allow-bean-definition-overriding: true
  redis:
    port: 6379
    host: 192.168.1.105
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        min-idle: 0
        max-idle: 8

test:
  value: beanCycle