server:
  port: 8088

spring:
  redis:
    port: 6379
    host: 192.168.1.105
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        min-idle: 0
        max-idle: 8

test:
  value: beanCycle